name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# env:
#   OPENAI_API_KEY: ${{ inputs.openai_api_key }}

# Define your inputs here.
inputs:
  openai_api_key:
    description: 'Your input description here'
    required: true
    default: ''

# Define your outputs here.
outputs:
  result:
    description: 'The output description here.'

runs:
  using: node20
  main: dist/index.js
