name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    environment: default

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Print Environment Variables
        id: env
        run: echo "OpenAI API Key $OPENAI_API_KEY"

      - name: Test Local Action
        id: test-action
        uses: aron-denenberg/ts-node-action@v1
        with:
          milliseconds: 2000
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.result }}"
