name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Print Environment Variables
        id: env
        run: echo "OpenAI API Key exists?"

      - name: Test Local Action
        id: test-action
        uses: aron-denenberg/ts-node-action@v1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          field: 'Code Change Summary'
          existing_value: '- Added new notification types to handle "device unlock order placed" and "device unlock order completed" events, including necessary template IDs. - Updated the name of the existing notification type from DeviceUnlockOrderPlacedConfirmation to DeviceUnlockOrderPlaced.'
          summary: 'This pull request includes new migration scripts to add and update notification types related to device unlock orders. The most important changes include adding new notification types and updating the name of an existing notification type. Additionally, the store-ui is updated to show the new notifications types and will no longer show the replacement types.'

      - name: Print Output
        id: output
        run:
          echo "${{ steps.test-action.outputs.result }}"
